#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> Restorebraine iOS setup"
echo "    Repo: $ROOT"
echo

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: not inside the restorebraine git repo."
  exit 1
fi

BRANCH="${1:-cursor/fix-native-xcode-coding-bacf}"
echo "==> Discarding local iOS build artifacts (safe — regenerated by npm run build)"
git checkout -- ios/App/App.xcodeproj/project.pbxproj 2>/dev/null || true
git checkout -- ios/App/App/public/index.html 2>/dev/null || true
git checkout -- src/lib/build-info.js 2>/dev/null || true
git checkout -- ios/App/App/BUILD_STAMP.txt 2>/dev/null || true
git checkout -- ios/App/App/capacitor.config.json 2>/dev/null || true

echo "==> Pulling latest $BRANCH"
git pull origin "$BRANCH"

echo "==> Installing npm dependencies (required after every pull)"
npm install

echo "==> Building web app + syncing iOS bundle"
npm run ios:prepare

echo "==> Installing CocoaPods"
cd ios/App
pod install

echo
echo "==> Done. Opening Xcode workspace..."
open App.xcworkspace

echo
echo "In Xcode: delete app from iPhone → Product → Clean Build Folder → Run"
echo "On device: look for badge bottom-left showing 'kbrown native v19'"
