#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> Restorebraine iOS setup"
echo "    Repo: $ROOT"
echo

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: not inside the restorebraine git repo."
  exit 1
fi

BRANCH="${1:-cursor/fix-native-xcode-coding-bacf}"

discard_regenerated_artifacts() {
  echo "==> Discarding local iOS/npm build artifacts (safe — regenerated by npm run build)"

  git checkout -- \
    ios/App/App.xcodeproj/project.pbxproj \
    ios/App/App/BUILD_STAMP.txt \
    ios/App/App/capacitor.config.json \
    ios/App/Podfile \
    package-lock.json \
    src/lib/build-info.js \
    public/AppIcon.png \
    2>/dev/null || true

  git checkout -- ios/App/App/Assets.xcassets/AppIcon.appiconset/ 2>/dev/null || true
  git clean -fd -- ios/App/App/Assets.xcassets/AppIcon.appiconset/ 2>/dev/null || true

  if [ -d ios/App/App/public ]; then
    git checkout -- ios/App/App/public/ 2>/dev/null || true
    git clean -fd -- ios/App/App/public/ 2>/dev/null || true
  fi

  if [ -d ios/App/App/Assets.xcassets ]; then
    git checkout -- ios/App/App/Assets.xcassets/ 2>/dev/null || true
    git clean -fd -- ios/App/App/Assets.xcassets/ 2>/dev/null || true
  fi
}

pull_latest() {
  echo "==> Fetching origin/$BRANCH"
  git fetch origin "$BRANCH"

  echo "==> Pulling latest $BRANCH"
  if git pull --ff-only origin "$BRANCH"; then
    return 0
  fi

  echo
  echo "Pull blocked by leftover local files — resetting generated paths and retrying..."
  discard_regenerated_artifacts

  if git pull --ff-only origin "$BRANCH"; then
    return 0
  fi

  echo
  echo "Pull still blocked — hard reset to origin/$BRANCH (drops local iOS/npm file edits only in this repo)."
  git reset --hard "origin/$BRANCH"
  git clean -fd -- ios/App/App/public/ ios/App/App/Assets.xcassets/AppIcon.appiconset/ 2>/dev/null || true
}

discard_regenerated_artifacts
pull_latest

echo "==> Installing npm dependencies (required after every pull)"
npm install

node scripts/generate-ios-app-icons.mjs

echo "==> Building web app + syncing iOS bundle"
npm run ios:prepare

STAMP="$(tr -d '\n' < ios/App/App/BUILD_STAMP.txt)"
echo "Build stamp: $STAMP"

if grep -q '"url".*restorebraine.base44.app' ios/App/App/capacitor.config.json 2>/dev/null; then
  echo
  echo "ERROR: ios/App/App/capacitor.config.json still has server.url."
  echo "       The native app will load the wrong Base44 login page until this is removed."
  echo "       Run: npm run build"
  exit 1
fi

if ! echo "$STAMP" | grep -q 'kbrown native v4[89]\|kbrown native v[5-9]'; then
  echo
  echo "WARNING: BUILD_STAMP looks old ($STAMP)."
  echo "         Expected v49 or newer. If Xcode still shows the wrong login page, delete the app and rebuild."
fi

echo "==> capacitor.config.json (must NOT contain server.url):"
grep -n 'url' ios/App/App/capacitor.config.json || echo "  (no url key — correct)"

echo "==> Installing CocoaPods"
cd ios/App
pod install

echo
echo "==> Done. Opening Xcode workspace..."
open App.xcworkspace

echo
echo "In Xcode: delete app from iPhone → Product → Clean Build Folder → Run"
echo "Expected build stamp after install: $STAMP"
echo
echo "Verify on Mac:"
echo "  cat ios/App/App/BUILD_STAMP.txt"
echo "  grep url ios/App/App/capacitor.config.json   # must NOT show restorebraine.base44.app url"
