#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> Restorebraine iOS setup"
echo "    Repo: $ROOT"
echo

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: not inside the restorebraine git repo."
  exit 1
fi

BRANCH="${1:-cursor/fix-native-xcode-coding-bacf}"

discard_regenerated_artifacts() {
  echo "==> Discarding local iOS build artifacts (safe — regenerated by npm run build)"

  git checkout -- \
    ios/App/App.xcodeproj/project.pbxproj \
    ios/App/App/BUILD_STAMP.txt \
    src/lib/build-info.js \
    public/AppIcon.png \
    2>/dev/null || true

  if [ -d ios/App/App/public ]; then
    git checkout -- ios/App/App/public/ 2>/dev/null || true
    git clean -fd -- ios/App/App/public/ 2>/dev/null || true
  fi

  if [ -d ios/App/App/Assets.xcassets ]; then
    git checkout -- ios/App/App/Assets.xcassets/ 2>/dev/null || true
    git clean -fd -- ios/App/App/Assets.xcassets/ 2>/dev/null || true
  fi
}

discard_regenerated_artifacts

echo "==> Pulling latest $BRANCH"
if ! git pull --ff-only origin "$BRANCH"; then
  echo
  echo "Pull blocked by leftover local files — resetting generated paths and retrying once..."
  discard_regenerated_artifacts
  git pull --ff-only origin "$BRANCH"
fi

echo "==> Installing npm dependencies (required after every pull)"
npm install

node scripts/generate-ios-app-icons.mjs

echo "==> Building web app + syncing iOS bundle"
npm run ios:prepare

if grep -q '"url".*restorebraine.base44.app' ios/App/App/capacitor.config.json 2>/dev/null; then
  echo "ERROR: ios/App/App/capacitor.config.json still has server.url — native will load the wrong login page."
  exit 1
fi
echo "Build stamp: $(tr -d '\n' < ios/App/App/BUILD_STAMP.txt)"

echo "==> Installing CocoaPods"
cd ios/App
pod install

STAMP=""
if [ -f "$ROOT/ios/App/App/BUILD_STAMP.txt" ]; then
  STAMP="$(tr -d '\n' < "$ROOT/ios/App/App/BUILD_STAMP.txt")"
fi

echo
echo "==> Done. Opening Xcode workspace..."
open App.xcworkspace

echo
echo "In Xcode: delete app from iPhone → Product → Clean Build Folder → Run"
if [ -n "$STAMP" ]; then
  echo "Expected build stamp after install: $STAMP"
else
  echo "Check ios/App/App/BUILD_STAMP.txt for the expected native build version."
fi
